### PR TITLE
renamed images and added alt

### PR DESCRIPTION
**Pull request by UshasriMavuri1999**

### CODE REVIEW

**Comment by harshgoel05** [comment]
Please solve the merge conflicts and make a PR again @UshasriMavuri1999

**Comment by UshasriMavuri1999** [comment]
Yeah done with those conflicts:)

**Comment by harshgoel05** [comment]
Ah, I'm sorry but it's still in conflict I guess its due to some other PR being merged. Please do check 😄

**Comment by UshasriMavuri1999** [comment]
> Ah, I'm sorry but it's still in conflict I guess its due to some other PR being merged. Please do check 😄

Those conflicts are just marking automatically changes that I made, anyways I reviewed those conflicts again

**Comment by UshasriMavuri1999** [comment]
> Ah, I'm sorry but it's still in conflict I guess its due to some other PR being merged. Please do check 😄

Yeah I saw that my changes are not updated...

**Pull request closed without merging**
