### PR TITLE
Added aos in home and services

### PR DESCRIPTION
**Pull request by Divyanshwick**

### CODE REVIEW

**Comment by Divyanshwick** [comment]
Brother you had assigned this issue to me, how could someone who had not been assigned can make a pr, and please take a look at this , I think it looks much better than the earlier

**Comment by Divyanshwick** [comment]
@harshgoel05 ??

**Comment by harshgoel05** [comment]
I will check it out, sorry my bad. I thought it was assigned to that person. I will check it and merge.

**Comment by harshgoel05** [comment]
Looks good to me! 🚀 Closing #8

**Comment by Divyanshwick** [comment]
You haven't merged it?

**Comment by Divyanshwick** [comment]
@harshgoel05  instead of closing #8 you have closed my pr #12

**Comment by Divyanshwick** [comment]
@harshgoel05 ??

**Pull request merged**
